[package]
name = "neve-lexer"
description = "Lexical analysis for Neve"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
neve-common.workspace = true
neve-diagnostic.workspace = true
logos.workspace = true
