[package]
name = "neve-diagnostic"
description = "Diagnostic and error reporting for Neve"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
neve-common.workspace = true
ariadne.workspace = true
thiserror.workspace = true
