[package]
name = "neve-fmt"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neve-lexer.workspace = true
neve-syntax.workspace = true
neve-parser.workspace = true

[dev-dependencies]
